;;; init-navigation-test.el --- Tests for navigation and workspaces -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'init-navigation)

(ert-deftest my/navigation-enables-the-modern-minibuffer-stack ()
  (should vertico-mode)
  (should marginalia-mode)
  (should which-key-mode)
  (should vertico-cycle)
  (should (= vertico-count 12))
  (should enable-recursive-minibuffers)
  (should completion-ignore-case)
  (should (equal completion-styles '(orderless basic)))
  (should (memq #'cursor-intangible-mode minibuffer-setup-hook)))

(ert-deftest my/navigation-uses-consult-for-common-jumps ()
  (should (eq (lookup-key global-map (kbd "C-s")) #'consult-line))
  (should (eq (lookup-key global-map (kbd "C-x b")) #'consult-buffer))
  (should (eq (lookup-key global-map (kbd "C-x p b"))
              #'consult-project-buffer))
  (should (eq (lookup-key global-map (kbd "M-y")) #'consult-yank-pop))
  (should (eq consult-buffer-list-function #'consult--frame-buffer-list))
  (should (eq xref-show-definitions-function #'consult-xref)))

(ert-deftest my/navigation-provides-embark-context-actions ()
  (should (locate-library "embark"))
  (should (locate-library "embark-consult"))
  (should (require 'embark nil t))
  (should (require 'embark-consult nil t))
  (should (eq (lookup-key global-map (kbd "C-.")) #'embark-act))
  (should (eq (lookup-key global-map (kbd "C-;")) #'embark-dwim))
  (should (eq prefix-help-command #'embark-prefix-help-command)))

(ert-deftest my/workspace-enables-lightweight-project-tabs ()
  (should tab-bar-mode)
  (should tab-bar-history-mode)
  (should (= tab-bar-show 1))
  (should-not tab-bar-close-button-show)
  (should-not tab-bar-new-button-show)
  (should (equal tab-bar-format
                 '(tab-bar-format-tabs tab-bar-separator)))
  (should (member '(my/workspace-open-current-project "Workspace" ?w)
                  project-switch-commands))
  (should (eq (lookup-key global-map (kbd "C-c w")) my/workspace-map))
  (should (eq (lookup-key my/workspace-map (kbd "p"))
              #'my/workspace-open-project)))

(ert-deftest my/workspace-reuses-a-tab-named-after-the-project ()
  (let (selected-name opened-command opened-root)
    (cl-letf (((symbol-function 'project-root)
               (lambda (_project) "C:/code/WhiteNight/"))
              ((symbol-function 'project-name)
               (lambda (_project) "WhiteNight"))
              ((symbol-function 'tab-bar-switch-to-tab)
               (lambda (name) (setq selected-name name)))
              ((symbol-function 'call-interactively)
               (lambda (command &rest _)
                 (setq opened-command command
                       opened-root default-directory))))
      (my/workspace--open-project 'fake-project))
    (should (equal selected-name "WhiteNight"))
    (should (eq opened-command #'project-find-file))
    (should (equal (downcase opened-root)
                   (downcase "C:/code/WhiteNight/")))))

(ert-deftest my/workspace-prefix-controls-layout-without-global-arrow-keys ()
  (should (eq (lookup-key my/workspace-map (kbd "h")) #'windmove-left))
  (should (eq (lookup-key my/workspace-map (kbd "L"))
              #'windmove-swap-states-right))
  (should (eq (lookup-key my/workspace-map (kbd "]"))
              #'tab-bar-switch-to-next-tab))
  ;; Preserve IDE-style Shift+Arrow selection outside the workspace prefix.
  (should-not (eq (lookup-key global-map (kbd "S-<left>")) #'windmove-left)))

(provide 'init-navigation-test)
;;; init-navigation-test.el ends here
